### ISSUE TITLE
Is it possible for sharing the input data

### ISSUE THREAD

**Issue by Yusin2Chen** [tase-nikol/Quantum-Machine-Learning-Perspective-In-Gravitational-Waves-Signal-Classification#1]
Thank you for sharing so nice work~
I am wondering whether you would like to share the input files as follows:
gw_aug = '1tbOPduVlNrKX-D3AALsUOWR9NBuFAQyu'
nd_aug = '1ukwfUxQZQ9zfSfBvZz4h8cj5gkh0gXUL'

Best regards,
Yusin

**Comment by tase-nikol** [comment]
Thanks, for the feedack, I am going to upload them as soon as possible.

**Comment by Yusin2Chen** [comment]
> Thanks, for the feedack, I am going to upload them as soon as possible.

Thank you, very much~

**Comment by Yusin2Chen** [comment]
> Thank you for sharing so nice work~ I am wondering whether you would like to share the input files as follows: gw_aug = '1tbOPduVlNrKX-D3AALsUOWR9NBuFAQyu' nd_aug = '1ukwfUxQZQ9zfSfBvZz4h8cj5gkh0gXUL'
> 
> Best regards, Yusin

![406B1D57](https://user-images.githubusercontent.com/10829064/135162144-df07f7aa-2ffb-4a42-921f-521044170394.png)
